
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("391x402")
window.configure(bg = "#C0C0C0")


def button_log_in_click():
    print("button_2 clicked")
    login = login_entry.get()
    password = password_entry.get()

    stroka = f'Данные пользователя: login: {str(login)}, password:{str(password)}'
    messagebox.showinfo(title='название', message=stroka)

canvas = Canvas(
    window,
    bg = "#C0C0C0",
    height = 402,
    width = 391,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_question = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_question.place(
    x=2.0,
    y=381.0,
    width=18.0,
    height=18.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    195.0,
    301.0,
    image=entry_image_1
)
password_entry = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    show='*'
)
password_entry.place(
    x=73.0,
    y=291.0,
    width=244.0,
    height=18.0
)

canvas.create_text(
    73.0,
    273.0,
    anchor="nw",
    text="Пароль",
    fill="#FFFFFF",
    font=("Inter Bold", 14 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    195.0,
    246.0,
    image=entry_image_2
)
login_entry = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0

)
login_entry.place(
    x=73.0,
    y=236.0,
    width=244.0,
    height=18.0
)

canvas.create_text(
    73.0,
    218.0,
    anchor="nw",
    text="Логин",
    fill="#FFFFFF",
    font=("Inter Bold", 14 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_log_in = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=button_log_in_click,
    relief="flat"
)
button_log_in.place(
    x=284.0,
    y=343.0,
    width=67.0,
    height=26.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=186.0,
    y=343.0,
    width=66.0,
    height=26.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=50.0,
    y=343.0,
    width=106.88349151611328,
    height=25.967741012573242
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    195.0,
    94.0,
    image=image_image_1
)

canvas.create_text(
    108.0,
    54.0,
    anchor="nw",
    text="TETRIS",
    fill="#FFFFFF",
    font=("Inter Black", 48 * -1)
)

canvas.create_text(
    73.0,
    174.0,
    anchor="nw",
    text="Введите логин и пароль",
    fill="#FFFFFF",
    font=("Inter Bold", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
