
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("391x402")
window.configure(bg = "#D9D9D9")


canvas = Canvas(
    window,
    bg = "#D9D9D9",
    height = 402,
    width = 391,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=165.0,
    y=358.0,
    width=60.0,
    height=25.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=200.0,
    y=305.0,
    width=177.0,
    height=26.833343505859375
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=14.0,
    y=305.0,
    width=177.0,
    height=26.833343505859375
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    317.0,
    236.0,
    image=image_image_1
)

canvas.create_text(
    20.0,
    230.0,
    anchor="nw",
    text="Скорость падения",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    317.0,
    201.0,
    image=image_image_2
)

canvas.create_text(
    20.0,
    197.0,
    anchor="nw",
    text="Высота стакана",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    317.0,
    168.0,
    image=image_image_3
)

canvas.create_text(
    20.0,
    164.0,
    anchor="nw",
    text="Длина стакана",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=86.0,
    y=129.0,
    width=20.0,
    height=20.0
)

canvas.create_text(
    20.0,
    127.0,
    anchor="nw",
    text="Цвет",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    250.5,
    106.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=130.0,
    y=95.0,
    width=241.0,
    height=20.0
)

canvas.create_text(
    20.0,
    93.0,
    anchor="nw",
    text="Название",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    50.0,
    42.0,
    anchor="nw",
    text="Настройка уровня сложности",
    fill="#FFFFFF",
    font=("Inter Bold", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
